import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { GripVertical, ImageIcon, RotateCcw, Save } from "lucide-react";
import { toast } from "sonner";
import { AppLayout } from "@/components/AppLayout";
import { useAuth } from "@/lib/auth";
import { getReceiptDesign, getSettings, saveReceiptDesign } from "@/lib/db";
import type { ReceiptDesign, ReceiptElement } from "@/lib/types";

export const Route = createFileRoute("/receipt-designer")({
  head: () => ({ meta: [
    { title: "تصميم الفاتورة — نظام البقالة" }, { name: "description", content: "تصميم فاتورة الطابعة الحرارية بالسحب والترتيب" },
    { property: "og:title", content: "تصميم الفاتورة — نظام البقالة" }, { property: "og:description", content: "تصميم فاتورة الطابعة الحرارية بالسحب والترتيب" },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" },
  ] }), component: ReceiptDesigner,
});

function ReceiptDesigner() {
  const { user, ready } = useAuth(); const navigate = useNavigate(); const settings = getSettings();
  const [width, setWidth] = useState<58 | 80>(settings.paperWidth); const [design, setDesign] = useState<ReceiptDesign>(() => getReceiptDesign(settings.paperWidth)); const [selected, setSelected] = useState<ReceiptElement["id"]>("store"); const [dragged, setDragged] = useState<number | null>(null);
  useEffect(() => { if (ready && (!user || user.role !== "admin")) navigate({ to: user ? "/" : "/login" }); }, [ready, user, navigate]);
  if (!ready || !user || user.role !== "admin") return null;
  const changeWidth = (next: 58 | 80) => { setWidth(next); setDesign(getReceiptDesign(next)); };
  const update = (patch: Partial<ReceiptElement>) => setDesign({ ...design, elements: design.elements.map((e) => e.id === selected ? { ...e, ...patch } : e) });
  const active = design.elements.find((e) => e.id === selected);
  const moveDrop = (to: number) => { if (dragged === null || dragged === to) return; const next = [...design.elements]; const item = next[dragged]; if (!item) return; next.splice(dragged, 1); next.splice(to, 0, item); setDesign({ ...design, elements: next }); setDragged(null); };
  return <AppLayout><div className="p-6"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">تصميم الفاتورة</h1><p className="text-sm text-muted-foreground">اسحب العناصر لتغيير ترتيبها ثم عدّل العنصر المحدد</p></div><div className="flex gap-2"><button onClick={() => { setDesign(getReceiptDesign(width)); toast.info("تم استرجاع آخر تصميم محفوظ"); }} className="rounded-lg bg-secondary px-4 py-2"><RotateCcw className="ml-2 inline h-4 w-4"/>تراجع</button><button onClick={() => { saveReceiptDesign(design); toast.success("تم حفظ تصميم الفاتورة"); }} className="rounded-lg bg-primary px-4 py-2 font-bold text-primary-foreground"><Save className="ml-2 inline h-4 w-4"/>حفظ</button></div></div>
    <div className="grid gap-5 xl:grid-cols-[280px_1fr_320px]"><aside className="rounded-lg border border-border bg-card p-4"><h2 className="mb-3 font-bold">مقاس الورق</h2><div className="mb-5 grid grid-cols-2 gap-2"><button onClick={() => changeWidth(58)} className={`rounded-lg py-2 font-bold ${width === 58 ? "bg-primary text-primary-foreground" : "bg-secondary"}`}>58 ملم</button><button onClick={() => changeWidth(80)} className={`rounded-lg py-2 font-bold ${width === 80 ? "bg-primary text-primary-foreground" : "bg-secondary"}`}>80 ملم</button></div><h2 className="mb-3 font-bold">عناصر الفاتورة</h2><div className="space-y-2">{design.elements.map((element, index) => <button draggable onDragStart={() => setDragged(index)} onDragOver={(e) => e.preventDefault()} onDrop={() => moveDrop(index)} onClick={() => setSelected(element.id)} key={element.id} className={`flex w-full items-center gap-2 rounded-lg border p-3 text-right ${selected === element.id ? "border-primary bg-primary/10" : "border-border bg-secondary"}`}><GripVertical className="h-4 w-4 text-muted-foreground"/><span className="flex-1">{element.label}</span><span className="text-xs text-muted-foreground">{element.visible ? "ظاهر" : "مخفي"}</span></button>)}</div></aside>
      <main className="overflow-auto rounded-lg border border-border bg-secondary p-6"><div className="mx-auto min-h-[650px] bg-receipt p-4 text-receipt shadow-lg" style={{ width: `${width * 3.78}px` }} dir="rtl">{design.elements.filter((e) => e.visible).map((e) => <Preview key={e.id} element={e} design={design} store={settings.storeName}/>)}</div></main>
      <aside className="rounded-lg border border-border bg-card p-4"><h2 className="mb-4 font-bold">خصائص العنصر</h2>{active && <div className="space-y-4"><label className="flex items-center gap-3"><input type="checkbox" checked={active.visible} onChange={(e) => update({ visible: e.target.checked })}/><span>إظهار العنصر</span></label><Field label="حجم الخط"><input type="range" min="8" max="32" value={active.fontSize} onChange={(e) => update({ fontSize: Number(e.target.value) })} className="w-full"/><span>{active.fontSize}px</span></Field><Field label="نوع الخط"><select value={active.fontFamily} onChange={(e) => update({ fontFamily: e.target.value })} className="h-10 w-full rounded-lg bg-secondary px-3"><option>Cairo</option><option>Tajawal</option><option>Noto Kufi Arabic</option><option>Arial</option></select></Field><Field label="المحاذاة"><select value={active.align} onChange={(e) => update({ align: e.target.value as ReceiptElement["align"] })} className="h-10 w-full rounded-lg bg-secondary px-3"><option value="right">يمين</option><option value="center">وسط</option><option value="left">يسار</option></select></Field><label className="flex items-center gap-3"><input type="checkbox" checked={active.bold} onChange={(e) => update({ bold: e.target.checked })}/><span>خط عريض</span></label><label className="flex items-center gap-3"><input type="checkbox" checked={active.divider} onChange={(e) => update({ divider: e.target.checked })}/><span>خط فاصل</span></label>{active.id === "logo" && <label className="block cursor-pointer rounded-lg bg-secondary p-4 text-center"><ImageIcon className="mx-auto mb-2 h-6 w-6"/>رفع الشعار<input type="file" accept="image/*" className="hidden" onChange={(e) => { const file = e.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => setDesign({ ...design, logo: String(reader.result) }); reader.readAsDataURL(file); }}/></label>}</div>}<hr className="my-5 border-border"/><Field label="عنوان المتجر"><input value={design.address} onChange={(e) => setDesign({ ...design, address: e.target.value })} className="h-10 w-full rounded-lg bg-secondary px-3"/></Field><Field label="الهاتف"><input value={design.phone} onChange={(e) => setDesign({ ...design, phone: e.target.value })} className="h-10 w-full rounded-lg bg-secondary px-3"/></Field><Field label="الرسالة الختامية"><textarea value={design.footer} onChange={(e) => setDesign({ ...design, footer: e.target.value })} className="w-full rounded-lg bg-secondary p-3"/></Field></aside></div>
  </div></AppLayout>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1 block text-sm text-muted-foreground">{label}</span>{children}</label>; }
function Preview({ element, design, store }: { element: ReceiptElement; design: ReceiptDesign; store: string }) { let content: React.ReactNode = element.label; if (element.id === "logo") content = design.logo ? <img src={design.logo} alt="الشعار" className="mx-auto max-h-20 max-w-[55%]"/> : <div className="text-muted-receipt">الشعار</div>; if (element.id === "store") content = store; if (element.id === "contact") content = <>{design.address || "عنوان المتجر"}<br/>{design.phone || "رقم الهاتف"}</>; if (element.id === "invoice") content = "فاتورة رقم: 125"; if (element.id === "date") content = new Date().toLocaleString("ar-IQ"); if (element.id === "cashier") content = "الكاشير: المدير"; if (element.id === "items") content = <table className="w-full"><tbody><tr><td>طماطة</td><td>1.250 كغم</td><td>1,875</td></tr><tr><td>حليب</td><td>2</td><td>3,000</td></tr></tbody></table>; if (element.id === "totals") content = <><div className="flex justify-between"><b>الإجمالي</b><b>4,875 د.ع</b></div><div className="flex justify-between"><span>المدفوع</span><span>5,000</span></div><div className="flex justify-between"><span>الباقي</span><span>125</span></div></>; if (element.id === "footer") content = design.footer; return <section style={{ fontFamily: element.fontFamily, fontSize: element.fontSize, fontWeight: element.bold ? 700 : 400, textAlign: element.align, marginBottom: element.spacing, paddingBottom: element.divider ? 5 : 0, borderBottom: element.divider ? "1px dashed currentColor" : "none" }}>{content}</section>; }